# Generated by Django 5.1.4 on 2024-12-26 15:23

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_image_location_user_avatar_user_phone_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='roomowner',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='roomowner',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('avatar', 'Ảnh đại diện'), ('post', 'Ảnh bài đăng'), ('banner', 'Ảnh banner')], default='post', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='codes.image'),
        ),
        migrations.AddField(
            model_name='roomowner',
            name='images',
            field=models.ManyToManyField(related_name='roomowners', to='codes.image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codes.post'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='roomowner',
            name='people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roomowner',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dypt73wn0/image/upload/v1735226049/avatar-fb-mac-dinh-51nSxugr_mwqgny.jpg', max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Số điện thoại không hợp lệ.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('landlord', 'Chủ nhà trọ'), ('tenant', 'Người thuê trọ'), ('admin', 'Quản trị viên')], default='tenant', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('street', 'ward', 'district', 'city')},
        ),
    ]
