# Generated by Django 5.1.4 on 2024-12-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_alter_comment_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomOwner',
        ),
    ]
