# Generated by Django 5.1.4 on 2024-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0008_alter_image_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
