# Generated by Django 5.1.4 on 2024-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0009_user_city_user_district_user_street_user_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ward',
        ),
    ]
