# Generated by Django 5.1.4 on 2024-12-28 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0012_remove_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Email không hợp lệ.')]),
        ),
    ]
