# Generated by Django 5.1.4 on 2024-12-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
