# Generated by Django 5.1.4 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0019_alter_follow_followed_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
